services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  nodejs:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:

volumes:
  mysql-data:
