services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test

    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  nodejs:
    build: .
    ports:
      - "3000:3000"
      - "5173:5173"
      - "3001:3001"
    depends_on:
      - mysql
    command: npm run start-all

    networks:
      - backend

networks:
  backend:

volumes:
  mysql-data:
